ALTER TABLE QUESTION ALTER COLUMN COMMENT_COUNT integer DEFAULT 0 NOT NULL;
ALTER TABLE QUESTION ALTER COLUMN VIEW_COUNT integer DEFAULT 0 NOT NULL;
ALTER TABLE QUESTION ALTER COLUMN LIKE_COUNT integer DEFAULT 0 NOT NULL;